
app_key: <%= ENV["DROPBOX_APP_KEY"] %>
app_secret: <%= ENV["DROPBOX_APP_SECRET"] %>
access_token_secret: <%= ENV["DROPBOX_ACCESS_TOKEN_SECRET"] %>
access_token: <%= ENV["DROPBOX_ACCESS_TOKEN"] %>
user_id: "73938219"
access_type: "app_folder"